service: nest

plugins:
 - serverless-offline

provider:
 name: aws
 deploymentMethod: direct
 runtime: nodejs20.x
 stage: ${opt:stage, 'dev'}
 region: ap-southeast-1
 versionFunctions: false

functions:
#  main: # The name of the lambda function
#    # The module 'handler' is exported in the file 'src/lambda'
#    handler: src/serverless.handler
#    events:
#      - http:
#          method: any
#          path: /{any+}
  apiHandler:
    handler: ./dist/serverless.handler
    timeout: 900
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

# package:
#   exclude:
#     # - node_modules/**
#     # - '!node_modules/node-fetch/**'
#     - aws-sam/
#     - nest/
    