service: nest

plugins:
 - serverless-offline
 - serverless-webpack

provider:
 name: aws
 deploymentMethod: direct
 runtime: nodejs20.x
 stage: ${opt:stage, 'dev'}
 region: ap-southeast-1
 versionFunctions: false

functions:
  apiHandler:
    handler: ./dist/serverless.handler
    timeout: 900
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

# custom:
#   esbuild:
#     bundle: true
#     minify: false
#     sourcemap: true
#     exclude: 'aws-sdk'
#     target: node20
#     define:
#       'require.resolve': undefined
#     platform: node
#     concurrency: 10
# package:
#   exclude:
#     # - node_modules/**
#     # - '!node_modules/node-fetch/**'
#     - aws-sam/
#     - nest/
