apiHandler:
  handler: ./src/serverless.handler
  timeout: 900
  events:
    - http:
        method: ANY
        path: /
        cors: true
    - http:
        method: ANY
        path: '{proxy+}'
        cors: true